# Generated by Django 4.1.2 on 2022-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixausgaben',
            name='mandate_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
