# Generated by Django 4.1.2 on 2022-11-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0003_remove_fixausgaben_mandate_id_fixausgaben_iban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixausgaben',
            name='iban',
        ),
        migrations.AddField(
            model_name='fixausgaben',
            name='mandate_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
