# Generated by Django 4.1.2 on 2022-11-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0005_fixausgaben_creditor_iban_fixausgaben_debtor_iban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixausgaben',
            old_name='name',
            new_name='creditorName',
        ),
        migrations.AddField(
            model_name='fixausgaben',
            name='debtorName',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
