# Generated by Django 4.1.2 on 2022-11-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0006_rename_name_fixausgaben_creditorname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixausgaben',
            name='mandate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
