# Generated by Django 4.1.2 on 2022-11-08 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashapp', '0009_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionGroupIntermediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=400)),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_user', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_group', to='cashapp.group')),
            ],
        ),
    ]
