# Generated by Django 4.1.2 on 2022-11-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0010_transactiongroupintermediate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixausgaben',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fixausgaben',
            name='creditorName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fixausgaben',
            name='creditor_iban',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fixausgaben',
            name='debtorName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fixausgaben',
            name='debtor_iban',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fixincome',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fixincome',
            name='creditorName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fixincome',
            name='creditor_iban',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fixincome',
            name='debtorName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fixincome',
            name='debtor_iban',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
